export enum ActionType {
  FETCH_RECIPES = "FETCH_RECIPES",
  FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS",
  FETCH_RECIPES_ERROR = "FETCH_RECIPES_ERROR",
  FETCH_RECIPE = "FETCH_RECIPE",
  FETCH_RECIPE_SUCCESS = "FETCH_RECIPE_SUCCESS",
  FETCH_RECIPE_ERROR = "FETCH_RECIPE_ERROR",
  INCREASE_SERVINGS = "INCREASE_SERVINGS",
  INCREASE_SERVINGS_SUCCESS = "INCREASE_SERVINGS_SUCCESS",
  INCREASE_SERVINGS_ERROR = "INCREASE_SERVINGS_ERROR",
}
